
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  web:
    image: registry.gitlab.com/akshay312-group/order-system:latest
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db/orders_db
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
      - db
      - kafka-init
      
  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    #adding partitions after build
  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      echo 'waiting for kafka to start'
      while ! kafka-topics --bootstrap-server kafka:29092 --list ; do
          sleep 2
      done
      echo 'creating topic'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic orders_topic --partitions 10 --replication-factor 1

volumes:
  postgres_data:
